### ISSUE TITLE
NPE if @Id omitted

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast-incubator/spring-data-integrations-commons#24]
If the domain class is missing the ``@Id`` annotation on the keyspace, this is thrown on a save
```
java.lang.NullPointerException
	at org.springframework.data.repository.core.support.PersistentEntityInformation.getIdType(PersistentEntityInformation.java:60)
	at org.springframework.data.repository.core.support.AbstractEntityInformation.isNew(AbstractEntityInformation.java:52)
	at org.springframework.data.keyvalue.repository.support.SimpleKeyValueRepository.save(SimpleKeyValueRepository.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```

However, in Spring Data Keyvalue, this should be thrown instead
```
java.lang.IllegalArgumentException: No field annotated with interface org.springframework.data.annotation.Id found!
	at org.springframework.util.Assert.notNull(Assert.java:115)
	at org.springframework.data.repository.core.support.ReflectionEntityInformation.<init>(ReflectionEntityInformation.java:72)
	at org.springframework.data.repository.core.support.ReflectionEntityInformation.<init>(ReflectionEntityInformation.java:48)
```

**Comment by neilstevenson** [comment]
In Spring-Data-Keyvalue, find "I ``org.springframework.data.keyvalue.repository.SimpleKeyValueRepositoryUnitTests``

If the domain object "Foo" looks like this,
```
	static class Foo {
		private /*@Id*/ String id;
```
you get
```
java.lang.IllegalArgumentException: No field annotated with interface org.springframework.data.annotation.Id found!
	at org.springframework.util.Assert.notNull(Assert.java:115)
	at org.springframework.data.repository.core.support.ReflectionEntityInformation.<init>(ReflectionEntityInformation.java:72)
	at org.springframework.data.repository.core.support.ReflectionEntityInformation.<init>(ReflectionEntityInformation.java:48)
	at org.springframework.data.keyvalue.repository.SimpleKeyValueRepositoryUnitTests.setUp(SimpleKeyValueRepositoryUnitTests.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.mockito.internal.runners.JUnit45AndHigherRunnerImpl.run(JUnit45AndHigherRunnerImpl.java:37)
	at org.mockito.runners.MockitoJUnitRunner.run(MockitoJUnitRunner.java:62)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

```

**Comment by neilstevenson** [comment]
Re-create as https://github.com/hazelcast/spring-data-hazelcast/issues/13
